# -*- coding: utf-8 -*-
"""Timed captions: (scene seconds, [(cue start, text), ...]) per scene."""
CUES = [
 (11, [(0, "Lutetium-177 DOTATATE: how a radioactive molecule treats a grade 1, stage 4 neuroendocrine tumour."),
       (5.5, "A targeting peptide, a chelator cage, and a radioactive payload — bolted permanently together.")]),
 (13, [(0, "Grade 1 means a Ki-67 index of 2% or less. The tumour divides reluctantly."),
       (4.5, "Stage 4 means it has already spread, in most midgut cases to the liver."),
       (9, "Too slow to attack with chemotherapy. Too scattered for surgery to reach.")]),
 (13, [(0, "Well-differentiated NET cells keep the machinery of their normal ancestors."),
       (4.5, "Including somatostatin receptor 2 — ten to a hundred times more of it."),
       (9, "So the arithmetic runs backwards: the lower the grade, the better the target.")]),
 (13, [(0, "Three parts, three jobs. Octreotate is the address: it locks onto the receptor."),
       (4.5, "DOTA is the cage. Without it a loose lutetium ion would drift to bone."),
       (9, "Lutetium-177 is the payload — a beta emitter with a 6.65-day half-life.")]),
 (13, [(0, "Swap the payload for gallium-68 and the same peptide becomes a PET tracer."),
       (4.5, "So the scan predicts exactly where the therapy will deposit its dose."),
       (9, "Uptake must exceed normal liver — Krenning 3 or 4 — or there is nothing to treat.")]),
 (14, [(0, "Infusion day starts with amino acids: lysine and arginine, half an hour ahead."),
       (5, "They saturate the kidney's reabsorption route, so the tubule is spared."),
       (9.5, "Then the therapy itself: 7.4 gigabecquerel, over thirty minutes.")]),
 (14, [(0, "The peptide binds, and the receptor drags the whole pair inside the cell."),
       (5, "A lysosome digests the peptide — but the caged metal cannot get back out."),
       (9.5, "The tumour holds it for days while the blood clears in hours. That gap is the treatment.")]),
 (14, [(0, "Every decay releases one electron, averaging 134 kiloelectronvolts."),
       (5, "It splits water into hydroxyl radicals, and strikes the DNA directly."),
       (9.5, "Both rails of the helix break at once. Repair is outrun, and the cell dies.")]),
 (14, [(0, "That electron travels half a millimetre to two millimetres through tissue."),
       (5, "Dozens of cells deep — so neighbours carrying no receptor are irradiated too."),
       (9.5, "The same physics puts dose in kidneys, marrow and spleen. Those set the ceiling.")]),
 (13, [(0, "Four infusions, eight weeks apart: 29.6 gigabecquerel over about eight months."),
       (4.5, "Blood counts and kidney function are checked before every cycle."),
       (9, "And a scan the next day confirms where the dose actually landed.")]),
 (13, [(0, "NETTER-1 randomised 229 patients with progressive midgut neuroendocrine tumours."),
       (4.5, "65% were progression-free at twenty months, against 11% on high-dose octreotide."),
       (9, "But tumours shrank in only 18%, and the survival gain was not significant.")]),
 (14, [(0, "A tumour that grows slowly also shrinks slowly. Response is read over months."),
       (5, "Early: fatigue, nausea, a dip in blood counts. Late: about a 2% risk of leukaemia."),
       (9.5, "Disease held still counts as success.")]),
 (9,  [(0, "Educational material — not medical advice.")]),
]
